service: serverless-nodejs-scraper-rest-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getKey:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  setKey:
    handler: handler.handler
    events:
      - http:
          path: /
          method: post
          cors: true



